In [1]:
import numpy as np

### 1.	Array Creation
	Create a 1D array of numbers from 10 to 50.
	Create a 3x3 array of random numbers between 0 and 1.


In [2]:
_1d_array = np.arange(10,51)

In [3]:
_1d_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [5]:
_3x3_array = np.random.rand(3,3)

In [6]:
_3x3_array

array([[0.44699236, 0.68078969, 0.99423686],
       [0.85173865, 0.72488456, 0.16293088],
       [0.41165731, 0.13461133, 0.04982834]])

### 2.	Array Attributes
	Find the shape, size, and data type of the array you created in the previous task.


In [9]:
print(f'1D array shape:{_1d_array.shape}\n1D array size:{_1d_array.size}\n1D array datatype:{_1d_array.dtype}')

1D array shape:(41,)
1D array size:41
1D array datatype:int32


### 3.	Basic Operations
    Add 5 to every element of a 1D array.
	Multiply two 2D arrays element-wise.


In [10]:
_1d_array+5

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
       49, 50, 51, 52, 53, 54, 55])

In [12]:
a = np.array([[1,2,3],[3,4,5]])

In [13]:
b = np.array([[6,7,8],[3,9,1]])

In [14]:
a*b

array([[ 6, 14, 24],
       [ 9, 36,  5]])

### 4.	Indexing and Slicing
	Create a 5x5 array of integers from 1 to 25. Extract:
	The first row.
	The last column.
	A subarray of the first three rows and first two columns.


In [15]:
nums = np.arange(1,26).reshape(5,5)

In [16]:
nums

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [18]:
nums[0]

array([1, 2, 3, 4, 5])

In [19]:
nums[-1]

array([21, 22, 23, 24, 25])

In [25]:
nums[:3,:2]

array([[ 1,  2],
       [ 6,  7],
       [11, 12]])

### 5.	Aggregation
	Create a 10-element array of random integers between 1 and 100. Find:
	The maximum value.
	The minimum value.
	The mean and standard deviation.


In [38]:
array_10 = np.random.randint(1,101,10)

In [40]:
array_10

array([ 8, 73, 50, 41, 95, 86, 60, 95, 72, 30])

In [41]:
array_10.max()

95

In [42]:
array_10.min()

8

In [43]:
array_10.mean()

61.0

In [44]:
array_10.std()

27.375171232341177

#### 6.	Reshaping
    Convert a 1D array of numbers from 1 to 12 into a 3x4 matrix.


In [45]:
arra_1d = np.arange(1,13)

In [47]:
arra_1d.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### 7.	Broadcasting
	Create a 3x3 matrix of ones. Add a 1D array [1, 2, 3] to each row.


In [48]:
numpy_ones = np.ones((3,3))

In [50]:
numpy_ones+np.array([1,2,3])

array([[2., 3., 4.],
       [2., 3., 4.],
       [2., 3., 4.]])

### 8.	Filtering
	Create a 1D array of random integers between 1 and 50. Extract all elements that are divisible by 5


In [52]:
array_1_to_50 = np.arange(1,51)

In [55]:
divible_by_5 = array_1_to_50[array_1_to_50%5==0]

In [56]:
divible_by_5

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

### 9.	Matrix Multiplication
	Create two 2x2 matrices and perform matrix multiplication.


In [57]:
a = np.array([[1,2,3],[3,4,5]])
b = np.array([[6,7,8],[3,9,1]])
a*b

array([[ 6, 14, 24],
       [ 9, 36,  5]])

### 10.	Advanced Indexing
    Given a 4x4 array, use fancy indexing to extract the diagonal elements.


In [80]:
arr = np.array([[1, 2, 3,6],
                [4, 5, 6,2],
                [7, 8, 9,10],
               [10,11,12,15]])

In [81]:
index = np.arange(arr.shape[0])

### using advanced slicing

In [82]:
index

array([0, 1, 2, 3])

In [83]:
arr[index,index]

array([ 1,  5,  9, 15])

In [88]:
arr[1,1]

5

### using inbuild functions

In [66]:
np.diag(arr)

array([1, 5, 9])

In [67]:
np.diagonal(arr)

array([1, 5, 9])